// Topic 2 View: Alerts & Events (4625/4624 Visualizer, Threshold Logic, Incident vs Case)
import { store } from '../state/store.js';
import { renderEventVisualizer, initEventVisualizerEvents } from '../components/EventVisualizer.js';
import { renderProgressionPath } from '../components/ProgressionPath.js';
import { sound } from '../audio/soundEffects.js';

let activeConceptId = 'alert';

const CONCEPTS = [
  {
    id: 'event',
    name: 'EVENT',
    tag: 'FOUNDATIONAL TELEMETRY',
    summary: '“Something happened.”',
    detail: 'An observable occurrence in a computer system or network (e.g., a file written, a packet transmitted, a single login attempt). FinCorp generates 50,000+ events per second. 99.99% are completely routine.',
    example: 'Windows Event ID 4625: Jane Miller types the wrong password once at 10:30:01 AM.'
  },
  {
    id: 'alert',
    name: 'ALERT',
    tag: 'THRESHOLD TRIGGERED',
    summary: '“Something needs your attention.”',
    detail: 'A high-fidelity notification generated by detection logic when single or correlated events match an attack pattern, threshold anomaly, or threat signature. Alerts require human analyst triage.',
    example: 'SIEM Rule DET-WIN-0422 flags 18x 4625 failures in 84 seconds for Finance01.'
  },
  {
    id: 'investigation',
    name: 'INVESTIGATION',
    tag: 'ANALYST COGNITION',
    summary: '“Understanding the full story.”',
    detail: 'The methodical process where the L1 analyst inspects the entities (User, Host, IP), correlates timelines, checks helpdesk tickets, and determines whether activity is malicious or benign.',
    example: 'You checking if Jane changed her password, and discovering the 10:31:45 4624 successful logon.'
  },
  {
    id: 'incident',
    name: 'INCIDENT',
    tag: 'CONFIRMED SECURITY IMPACT',
    summary: '“An active security breach or unauthorized threat.”',
    detail: 'A confirmed violation or imminent threat of violation of security policy, acceptable use policy, or standard cybersecurity safety practices requiring coordinated active response.',
    example: 'An adversary successfully using stolen credentials to download executive salary databases.'
  },
  {
    id: 'case',
    name: 'CASE',
    tag: 'FORMAL AUDIT RECORD',
    summary: '“The documented investigation record.”',
    detail: 'The structured folder and audit trail containing analyst findings, linked telemetry, hypotheses, ticket numbers, communications, and final closing disposition.',
    example: 'Case ALT-2026-9042 documented in TheHive / Jira with full root cause analysis.'
  }
];

export function renderTopic2View() {
  const activeConcept = CONCEPTS.find(c => c.id === activeConceptId) || CONCEPTS[1];

  return `
    <div class="container animate-fade-in" style="padding-top: 1.5rem; padding-bottom: 5rem;">
      
      <!-- Module Progression Track -->
      ${renderProgressionPath('topic-2')}

      <!-- TOPIC HERO -->
      <section style="margin-bottom: 3rem;">
        <div style="display: flex; align-items: center; gap: 0.65rem; margin-bottom: 0.75rem;">
          <span class="genz-badge badge-alert">TOPIC 02 • 10:32 AM</span>
          <span class="mono-data">THE ANATOMY OF TELEMETRY</span>
        </div>

        <h1 style="margin-bottom: 1rem;">
          Alerts & <span class="gradient-text-cyan">Events.</span>
        </h1>

        <div class="glass-panel" style="padding: 1.5rem 2rem; background: rgba(10, 16, 31, 0.85); border-left: 4px solid var(--danger); margin-bottom: 2.5rem;">
          <div style="font-family: var(--font-mono); font-size: 0.8rem; color: #fca5a5; margin-bottom: 0.4rem; text-transform: uppercase;">
            SHIFT CONTEXT • 10:32 AM EST
          </div>
          <p style="font-size: 1.05rem; color: var(--text-bright); line-height: 1.65;">
            "You click the flashing alert on your FinCorp dashboard. Before jumping to wild conclusions, you must distinguish between 
            the building blocks of cybersecurity operations: <strong>What is a raw Event? How does it become an Alert? When does it become an Incident? And why is every investigation tracked in a Case?</strong>"
          </p>
        </div>
      </section>

      <!-- VISUAL PROGRESSION PIPELINE -->
      <section style="margin-bottom: 4rem;">
        <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem; flex-wrap: wrap; gap: 0.5rem;">
          <div>
            <span class="genz-badge badge-try-it">THE TELEMETRY PYRAMID</span>
            <h2 style="font-size: 1.6rem; color: var(--text-bright); margin-top: 0.35rem;">
              Event ➔ Alert ➔ Investigation ➔ Incident ➔ Case
            </h2>
          </div>
          <div style="font-size: 0.82rem; color: var(--cyan-text); font-family: var(--font-mono);">
            CLICK ANY CONCEPT TO INSPECT DEFINITION
          </div>
        </div>

        <!-- Horizontal Flow Buttons -->
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 0.85rem; margin-bottom: 1.5rem;">
          ${CONCEPTS.map(c => `
            <div class="glass-panel ${c.id === activeConceptId ? 'glass-panel-cyan' : ''}" 
                 data-concept-id="${c.id}" 
                 style="padding: 1.25rem 1rem; cursor: pointer; text-align: center; border-color: ${c.id === activeConceptId ? 'var(--cyan-primary)' : 'var(--border-subtle)'}; background: ${c.id === activeConceptId ? 'rgba(0, 242, 254, 0.1)' : 'var(--bg-card)'};">
              <span class="genz-badge ${c.id === 'incident' ? 'badge-alert' : (c.id === 'alert' ? 'badge-scenario' : 'badge-tech-box')}" style="font-size: 0.65rem; margin-bottom: 0.5rem;">
                ${c.tag}
              </span>
              <div style="font-weight: 800; font-size: 1.1rem; color: var(--text-bright); margin-bottom: 0.25rem;">
                ${c.name}
              </div>
              <div style="font-size: 0.8rem; color: var(--text-secondary); font-style: italic;">
                ${c.summary}
              </div>
            </div>
          `).join('')}
        </div>

        <!-- Concept Inspector Card -->
        <div class="glass-panel" style="padding: 2rem; background: rgba(14, 21, 38, 0.95); border-color: rgba(0, 242, 254, 0.35);">
          <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem; flex-wrap: wrap; gap: 0.5rem;">
            <div style="display: flex; align-items: center; gap: 0.75rem;">
              <span class="genz-badge badge-key-idea">${activeConcept.tag}</span>
              <h3 style="font-size: 1.4rem; color: var(--text-bright); font-weight: 800;">${activeConcept.name} — ${activeConcept.summary}</h3>
            </div>
            <span class="mono-data">FinCorp SOC SOP Glossary</span>
          </div>

          <p style="font-size: 1.05rem; color: var(--text-main); line-height: 1.65; margin-bottom: 1.25rem;">
            ${activeConcept.detail}
          </p>

          <div style="background: rgba(0, 242, 254, 0.05); border: 1px solid rgba(0, 242, 254, 0.2); border-radius: 8px; padding: 1.1rem;">
            <span style="font-size: 0.75rem; font-family: var(--font-mono); color: var(--cyan-primary); font-weight: 700;">REAL-WORLD FINCORP EXAMPLE:</span>
            <div style="font-size: 0.92rem; color: var(--text-bright); margin-top: 0.35rem; font-family: var(--font-mono);">
              ${activeConcept.example}
            </div>
          </div>
        </div>
      </section>

      <!-- EVENT VISUALIZER: 18x 4625 + 1x 4624 -->
      <section style="margin-bottom: 4rem;">
        <div style="display: flex; align-items: center; gap: 0.65rem; margin-bottom: 0.5rem;">
          <span class="genz-badge badge-demo">INTERACTIVE LOG STREAM</span>
          <span style="font-size: 0.85rem; color: var(--text-muted); font-family: var(--font-mono);">EVENT ID 4625 & 4624</span>
        </div>
        <h2 style="font-size: 1.8rem; margin-bottom: 0.75rem;">
          The Finance01 Event Stream
        </h2>
        <p style="font-size: 1rem; color: var(--text-secondary); max-width: 800px; margin-bottom: 1.5rem;">
          Watch the sequential stream of authentication attempts logged by the Windows Security subsystem on workstation <span class="mono-data">FIN-PC-04</span>. Click any event to inspect its caller process and hex substatus codes.
        </p>

        <div id="event-visualizer-container">
          ${renderEventVisualizer()}
        </div>
      </section>

      <!-- TECH BOXES: EVENT IDS -->
      <section style="margin-bottom: 4rem;">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem;">
          
          <!-- Event 4625 -->
          <div class="callout-box callout-alert-box">
            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.75rem;">
              <span class="event-id-badge event-id-4625">EVENT ID 4625</span>
              <span class="genz-badge badge-tech-box">LOGON FAILURE</span>
            </div>
            <h4 style="font-size: 1.15rem; color: #fca5a5; margin-bottom: 0.5rem;">
              Windows Authentication Failure
            </h4>
            <p style="font-size: 0.9rem; color: var(--text-bright); line-height: 1.6; margin-bottom: 0.85rem;">
              Generated whenever a logon request fails for any reason (wrong password, unknown username, expired account, clock skew, or lockout).
            </p>
            <div style="font-size: 0.82rem; color: var(--text-secondary); background: rgba(0,0,0,0.3); padding: 0.75rem; border-radius: 6px;">
              <strong>Key Substatus Code:</strong> <span class="mono-data" style="color: #fca5a5;">0xC000006A</span> means the account username was valid, but the password provided was bad.
            </div>
          </div>

          <!-- Event 4624 -->
          <div class="callout-box" style="background: rgba(12, 32, 24, 0.85); border: 1px solid rgba(16, 185, 129, 0.4);">
            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.75rem;">
              <span class="event-id-badge event-id-4624">EVENT ID 4624</span>
              <span class="genz-badge badge-try-it">LOGON SUCCESS</span>
            </div>
            <h4 style="font-size: 1.15rem; color: #86efac; margin-bottom: 0.5rem;">
              Windows Authentication Success
            </h4>
            <p style="font-size: 0.9rem; color: var(--text-bright); line-height: 1.6; margin-bottom: 0.85rem;">
              Generated when a logon session is successfully authenticated. Crucial for establishing valid user presence and activity baselines.
            </p>
            <div style="font-size: 0.82rem; color: var(--text-secondary); background: rgba(0,0,0,0.3); padding: 0.75rem; border-radius: 6px;">
              <strong>Logon Type 2:</strong> Interactive logon (local keyboard/display). Proves physical console presence at the workstation.
            </div>
          </div>

        </div>
      </section>

      <!-- INCIDENT VS CASE INTERACTIVE DECISION -->
      <section style="margin-bottom: 4rem;">
        <div class="glass-panel" style="padding: 2rem; background: rgba(15, 23, 42, 0.9); border: 1px solid var(--border-medium);">
          <div style="display: flex; align-items: center; gap: 0.65rem; margin-bottom: 0.75rem;">
            <span class="genz-badge badge-scenario">🎯 OPERATIONAL PRINCIPLE</span>
            <span style="font-size: 0.85rem; color: var(--text-muted); font-family: var(--font-mono);">DOES EVERY ALERT BECOME AN INCIDENT?</span>
          </div>

          <h3 style="font-size: 1.4rem; color: var(--text-bright); margin-bottom: 1rem;">
            "Does every alert become an incident?"
          </h3>

          <div style="display: flex; gap: 1rem; margin-bottom: 1.5rem;">
            <button id="btn-inc-yes" class="btn btn-secondary" style="font-size: 0.95rem; padding: 0.65rem 1.75rem;">
              YES — Every alert is an incident
            </button>
            <button id="btn-inc-no" class="btn btn-primary" style="font-size: 0.95rem; padding: 0.65rem 1.75rem;">
              NO — Only confirmed security threats become incidents
            </button>
          </div>

          <div id="inc-explanation" class="animate-fade-in" style="background: rgba(0, 242, 254, 0.05); border: 1px solid rgba(0, 242, 254, 0.25); border-radius: 8px; padding: 1.25rem;">
            <div style="font-weight: 700; color: var(--cyan-primary); font-size: 1.05rem; margin-bottom: 0.5rem;">
              Correct! Not every alert becomes an incident.
            </div>
            <p style="font-size: 0.92rem; color: var(--text-bright); line-height: 1.6;">
              In a typical enterprise SOC, over <strong>70% to 85% of alerts</strong> are triaged and dismissed as False Positives, Expected Activity, or Benign Positives! If every alert triggered an incident declaration, Incident Response teams would be overwhelmed and catastrophic real breaches would slip through.
            </p>
            <div style="margin-top: 0.75rem; font-size: 0.85rem; color: var(--text-secondary);">
              <strong>Remember:</strong> <em>Not every event becomes an alert. Not every alert becomes an incident. But every investigation MUST be documented in a Case!</em>
            </div>
          </div>
        </div>
      </section>

      <!-- QUICK CHECK QUIZ -->
      <section style="margin-bottom: 4rem;">
        <div class="glass-panel" style="padding: 2rem; background: rgba(14, 21, 38, 0.9); border: 1px solid rgba(236, 72, 153, 0.4);">
          <div style="display: flex; align-items: center; gap: 0.6rem; margin-bottom: 0.5rem;">
            <span class="genz-badge badge-quiz">📝 QUICK CHECK</span>
            <span style="font-size: 0.85rem; color: #f472b6; font-family: var(--font-mono);">STAGE 02 QUIZ</span>
          </div>
          <h3 style="font-size: 1.3rem; color: var(--text-bright); margin-bottom: 0.5rem;">
            Match the cybersecurity scenario to its correct classification:
          </h3>
          <p style="font-size: 0.88rem; color: var(--text-secondary); margin-bottom: 1.25rem;">
            "A documented investigation folder created in the ticketing system to record findings, evidence, and closing notes."
          </p>

          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 0.85rem; margin-bottom: 1.5rem;" id="quiz-t2-options">
            <div class="option-card" data-quiz-opt="event">
              <span class="genz-badge badge-tech-box">EVENT</span>
            </div>
            <div class="option-card" data-quiz-opt="alert">
              <span class="genz-badge badge-scenario">ALERT</span>
            </div>
            <div class="option-card" data-quiz-opt="incident">
              <span class="genz-badge badge-alert">INCIDENT</span>
            </div>
            <div class="option-card" data-quiz-opt="case">
              <span class="genz-badge badge-demo">CASE</span>
            </div>
          </div>

          <div id="quiz-t2-feedback" style="display: none; padding: 1rem; border-radius: 8px; font-size: 0.9rem;"></div>
        </div>
      </section>

      <!-- ADVANCE TO TOPIC 3 CTA -->
      <div style="display: flex; justify-content: flex-end;">
        <button id="btn-next-topic-3" class="btn btn-primary" style="font-size: 1.05rem; padding: 0.85rem 2.2rem; box-shadow: 0 0 25px var(--cyan-glow);">
          Proceed to Topic 03: Alert Triage →
        </button>
      </div>

    </div>
  `;
}

export function initTopic2Events() {
  initEventVisualizerEvents();

  // Concept selector
  document.querySelectorAll('[data-concept-id]').forEach(el => {
    el.addEventListener('click', (e) => {
      const id = e.currentTarget.getAttribute('data-concept-id');
      if (id) {
        activeConceptId = id;
        sound.playClick();
        const app = document.getElementById('view-container');
        if (app) {
          app.innerHTML = renderTopic2View();
          initTopic2Events();
        }
      }
    });
  });

  // Incident vs Case Buttons
  const btnYes = document.getElementById('btn-inc-yes');
  const btnNo = document.getElementById('btn-inc-no');
  const explanation = document.getElementById('inc-explanation');

  if (btnYes) {
    btnYes.addEventListener('click', () => {
      sound.playClick();
      if (explanation) {
        explanation.innerHTML = `<div style="color: #fde68a;"><strong>Not quite.</strong> If every single alert became an incident, SOC analysts would drown in paperwork and genuine cyberattacks would be missed. Only validated, high-risk security threats become incidents.</div>`;
      }
    });
  }

  if (btnNo) {
    btnNo.addEventListener('click', () => {
      sound.playSuccess();
      store.completeCheckpoint('check-inc-vs-case', 35, 'Mastered Incident vs Case Principles');
      if (explanation) {
        explanation.innerHTML = `<div style="color: #86efac; font-weight: 700;">Spot on! Only confirmed, actionable security events warrant full incident response declaration.</div>`;
      }
    });
  }

  // Quiz 2
  document.querySelectorAll('#quiz-t2-options .option-card').forEach(card => {
    card.addEventListener('click', (e) => {
      const opt = e.currentTarget.getAttribute('data-quiz-opt');
      const feedback = document.getElementById('quiz-t2-feedback');

      document.querySelectorAll('#quiz-t2-options .option-card').forEach(c => {
        c.classList.remove('selected-correct', 'selected-wrong');
      });

      if (opt === 'case') {
        card.classList.add('selected-correct');
        sound.playSuccess();
        store.completeCheckpoint('check-t2-quiz', 50, 'Mastered Case Definition');
        store.completeTopic('topic-2');
        if (feedback) {
          feedback.style.display = 'block';
          feedback.style.background = 'rgba(16, 185, 129, 0.15)';
          feedback.style.border = '1px solid var(--success)';
          feedback.style.color = '#86efac';
          feedback.innerHTML = `<strong>Spot on!</strong> A <strong>CASE</strong> is the documented investigation record where all notes, artifacts, and decisions are officially stored for legal, compliance, and post-incident auditing.`;
        }
      } else {
        card.classList.add('selected-wrong');
        sound.playClick();
        if (feedback) {
          feedback.style.display = 'block';
          feedback.style.background = 'rgba(245, 158, 11, 0.15)';
          feedback.style.border = '1px solid var(--warning)';
          feedback.style.color = '#fde68a';
          feedback.innerHTML = `Not quite. Remember: An Event is something that happened. An Alert is a trigger requiring review. An Incident is a confirmed threat. The documented record itself is the <strong>CASE</strong>!`;
        }
      }
    });
  });

  const btnNext = document.getElementById('btn-next-topic-3');
  if (btnNext) {
    btnNext.addEventListener('click', () => {
      store.completeTopic('topic-2');
      store.navigate('topic-3', 3);
    });
  }
}
